"""Add description to TripStop

Revision ID: 2012ea6aa6b3
Revises: eb47040ee6b3
Create Date: 2026-08-22 14:47:12.149628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2012ea6aa6b3'
down_revision = 'eb47040ee6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
